#! /bin/bash

docker-compose down -v
docker-compose up -d
sleep 20

# configuring ttl for message in a queue to 86400000 = 24 hours
docker exec -it zokrates-worker_rabbitmq_1 rabbitmqctl set_policy TTL ".*" '{"message-ttl":86400000}' --apply-to queues
docker-compose logs -f
