name: Taxgrid Deploy

on:
  push:
    branches:
      - taxgrid

jobs:
  # define job to build and publish docker image
  build-and-push-taxgrid:
    name: Build Docker image and push to taxgrid
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/eyblockchain/taxgrid-api/tg-zokrates-worker:latest
