name: Docker Package

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: |
          npm ci
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: semantic release
        uses: codfish/semantic-release-action@master
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push version
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker login https://docker.pkg.github.com -u $GITHUB_ACTOR -p $GPR_TOKEN
          docker build --build-arg GPR_TOKEN=$GPR_TOKEN -t docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates-worker:$RELEASE_VERSION .
          docker push docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates-worker:$RELEASE_VERSION
        env:
          RELEASE_VERSION: v${{ steps.semantic.outputs.release-version }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
