name: Release Updated

on:
  push:
    branches:
      - swati/updates

jobs:
  # define job to build and publish docker image
  build-and-push:
    name: Build Docker image and push 
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm ci
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      #      - name: semantic release
      #        uses: codfish/semantic-release-action@master
      #        id: semantic
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push version
        run: |
          docker build --build-arg GPR_TOKEN=$GPR_TOKEN -t ghcr.io/eyblockchain/zokrates-worker-updated:latest .
          docker push ghcr.io/eyblockchain/zokrates-worker-updated:latest
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ghcr.io/eyblockchain/taxgrid-api/tg-zokrates-worker:latest




