name: Release updated

on:
  push:
    branches:
      - swati/updates

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    # - uses: codfish/semantic-release-action@master
    #   id: semantic
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Build docker  image
    #   run: docker build ./merkle-tree

    # - run: echo ${{ steps.semantic.outputs.release-version }}

    - name: Docker push version
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker login https://docker.pkg.github.com -u $GITHUB_ACTOR -p $GPR_TOKEN
          docker build --build-arg GPR_TOKEN=$GPR_TOKEN -t docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates-worker-updated:$RELEASE_VERSION .
          docker push docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates-worker-updated:$RELEASE_VERSION
        env:
          RELEASE_VERSION: v${{ steps.semantic.outputs.release-version }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}




