name: Release updated

on:
  push:
    branches:
      - swati/updates

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    # - uses: codfish/semantic-release-action@master
    #   id: semantic
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Build docker  image
    #   run: docker build ./merkle-tree

    # - run: echo ${{ steps.semantic.outputs.release-version }}

    - name: Build and push UI docker image
      uses: docker/build-push-action@v2
      with:
        build-args: |
          GPR_TOKEN=${{ secrets.GPR_TOKEN }}
        tags: |
          ghcr.io/eyblockchain/zokrates-worker-starlight-updated:latest
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
        push: true




