name: Mend SCA Scan
on:
  push:
    branches:
      - taxgrid

permissions:
  id-token: write
  contents: write
  actions: write
  deployments: write
  packages: write
  repository-projects: write

jobs:
  processes:
    runs-on: ubuntu-latest
    name: Mend 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm ci
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Download unified agent
        run: |
            curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }} 

      - name: Run whitesource unified agent
        run: |
            cat /home/runner/work/zokrates-worker/zokrates-worker/wss-unified-agent.config
            java -jar wss-unified-agent.jar -c /home/runner/work/zokrates-worker/zokrates-worker/wss-unified-agent.config -apikey $MEND_API_KEY -userkey $MEND_USER_KEY
        env:
          MEND_API_KEY: ${{ secrets.MEND_API_KEY }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}